name: 68publishers/asset checks
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  coding-style:
    name: Coding Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Make init
        run: make init

      - name: Php-Cs-Fixer
        run: make cs.check

      - name: PhpStan
        run: make stan

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Make init
        run: make init

      - name: Run tests [PHP 7.4]
        run: PHP=74 make tests.run

      - name: Run tests [PHP 8.0]
        run: PHP=80 make tests.run

      - name: Run tests [PHP 8.1]
        run: PHP=81 make tests.run

      - name: Run tests [PHP 8.2]
        run: PHP=82 make tests.run

  #coverage:
  #    - name: Checkout
  #      uses: actions/checkout@v2
  #      with:
  #        fetch-depth: 0

  #    - name: Make init
  #      run: make init

  #    - name: Generate the coverage report
  #      run: |
  #        make coverage
  #        vendor/bin/ocular code-coverage:upload --format=php-clover coverage.xml
